export const SET_ROLE = 'LOGIN_ACTION:SET_ROLE';
export const SET_IS_LOADING = 'LOGIN_ACTION:SET_IS_LOADING';
export const SET_USER = 'LOGIN_ACTION:SET_USER';
export const SET_CONTENT_IS_LOADING = 'GLOBAL_ACTION:SET_CONTENT_IS_LOADING';