import React from "react";
import CustomNode from "./CustomNode";

const getConfig = ({ width, height }) => ({
  automaticRearrangeAfterDropNode: false,
  directed: true,
  collapsible: false,
  focusAnimationDuration: 0.5,
  focusZoom: 3,
  highlightDegree: 1,
  highlightOpacity: 0.2,
  linkHighlightBehavior: true,
  maxZoom: 8,
  minZoom: 0.01,
  initialZoom: 0.25,
  nodeHighlightBehavior: true,
  panAndZoom: false,
  staticGraph: false,
  width,
  height,
  node: {
    color: "#d3d3d3",
    fontColor: "black",
    fontSize: 11,
    fontWeight: "normal",
    highlightColor: "red",
    highlightFontSize: 11,
    highlightFontWeight: "bold",
    highlightStrokeColor: "SAME",
    highlightStrokeWidth: 1.5,
    labelProperty: null,
    mouseCursor: "pointer",
    opacity: 1,
    renderLabel: false,
    size: {
      width: 1000,
      height: 1200,
    },
    strokeColor: "none",
    strokeWidth: 1.5,
    svg: "",
    symbolType: "star",
    viewGenerator: (node) => <CustomNode person={node} />,
  },
  d3: {
    alphaTarget: 1,
    gravity: -1300,
    linkLength: 350,
    linkStrength: 1,
  },
  link: {
    color: "#d3d3d3",
    opacity: 1,
    semanticStrokeWidth: false,
    strokeWidth: 4,
    highlightColor: "blue",
  },
});

export default getConfig;
