import React from "react";
import CustomNode from "./CustomNode";

export default {
  automaticRearrangeAfterDropNode: true,
    collapsible: true,
  height: 600,
  focusAnimationDuration: 0.75,
  focusZoom: 1,
  highlightDegree: 1,
  highlightOpacity: 0.2,
  linkHighlightBehavior: true,
  maxZoom: 8,
  minZoom: 0.1,
  initialZoom:0.9,
  nodeHighlightBehavior: true,
  panAndZoom: false,
  staticGraph: false,
  width: 1400,
  node: {
  color: "#d3d3d3",
    fontColor: "black",
    fontSize: 11,
    fontWeight: "normal",
    highlightColor: "red",
    highlightFontSize: 11,
    highlightFontWeight: "bold",
    highlightStrokeColor: "SAME",
    highlightStrokeWidth: 1.5,
    labelProperty:null,
    // labelClass: "person-node-label",
    mouseCursor: "pointer",
    opacity: 1,
    renderLabel: false,
    size: {
    width: 800,
      height: 900,
  },
  strokeColor: "none",
    strokeWidth: 1.5,
    svg: "",
    symbolType: "star",
    viewGenerator: node => <CustomNode person={node} />,
},
  d3: {
    alphaTarget: 1,
    gravity: -500,
    linkLength: 200,
    linkStrength: 1,
  },
  link: {
    color: "#d3d3d3",
      opacity: 1,
      semanticStrokeWidth: false,
      strokeWidth: 4,
      highlightColor: "blue",
  },
};
