# docker-compose for running backend server with reversed proxy
version: '3.9'

services:
  sbtree_backend:
    build: .
    restart: always
  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - "3002:443"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    depends_on:
      - sbtree_backend
