const getLocalization = () => ({
  people: "Люди",
  events: "Події",
  tree: "Дерево",
  logOut: "Вийти",
  login: "Увійти",
  profile: "Профіль",
  fullName: "ПІБ",
  status: "Статус",
  statuses: "Статуси",
  membership: "Членство",
  contact: "Контакти",
  description: "Опис",
  filters: "Фільтри",
  filter: "Фільтр",
  sortBy: "Сортувати за",
  from: "Від",
  to: "До",
  eventInfo: "Інформація про подію",
  name: "Назва",
  event: "Подія",
  category: "Категорія",
  date: "Дата проведення",
  members: "Учасники події",
  apply: "Застосувати",
  reset: "Скинути",
  cancel: "Відмінити",
  about: "Про себе",
  avatar: "Фото",
  retirement: "Дата пошанування",
  memberDate: "Дата висвяти",
  birthday: "Дата народження",
  patron: "Патрон",
  speciality: "Спеціальність",
  faculty: "Факультет",
  telephone: "Телефон",
  email: "Email",
  person: "Людина",
  image: "Картинка",
  eventStart: "Дата початку події",
  eventEnd: "Дата завершення події",
  shortDescription: "Короткий опис події",
  details: "Детальний опис події",
  uploadArea: "Перетягніть, або натисніть щоб завантажити файл",
  internalServerError: "Помилка сервера, зверніться до нас.",
  pendingResponse: "Проходить авторизація...",
  doNotHaveAccess: "Нажаль ви не маєте доступу, зверніться до нас",
  loginWithGoogle: "Увійти задопомогою Google",
  pageNotFound: "Сторінка не знайдена",
  goToTheTree: "Перейти на сторінку з Деревом",
  looksLikeError: "Виглядає наче сталася помилка",
  ops: "Ой",
  reqField: "Це поле не може бути пустим",
  jobDescription: "Опис вкладу",
  role: "Роль",
  activity: "Активність в події",
});

export const localization = getLocalization();
