export const SET_PEOPLE = "PEOPLE_ACTION:SET_PEOPLE";
export const SET_INSTANCE = "PEOPLE_ACTION:SET_INSTANCE";
export const SET_FILTER = "PEOPLE_ACTION:SET_FILTER";
export const SET_SORT = "PEOPLE_ACTION:SET_SORT";
export const SET_FULL_NAMES = "PEOPLE_ACTION:SET_FULL_NAMES";
export const SET_STATUSES = "PEOPLE_ACTION:SET_STATUSES";
export const SET_PAGE = "EVENT_ACTION:SET_PAGE";
export const SET_TOTAL_PAGES = "EVENT_ACTION:SET_TOTAL_PAGES";
